const weeklySchedule=[
  {weekday:0,hora:'09:00',titulo:'Escola Bíblica Dominical'},
  {weekday:0,hora:'19:00',titulo:'Culto da Família'},
  {weekday:3,hora:'19:30',titulo:'Culto de Ensino'},
  {weekday:5,hora:'19:30',titulo:'Culto de Oração'}
];
const dayNames=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const monthNames=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];
function generateRecurringEvents(daysAhead=45){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()),events=[];for(let offset=0;offset<daysAhead;offset++){const d=new Date(start);d.setDate(start.getDate()+offset);weeklySchedule.filter(s=>s.weekday===d.getDay()).forEach(s=>{const [h,m]=s.hora.split(':').map(Number),eventDate=new Date(d);eventDate.setHours(h,m,0,0);if(eventDate<now)return;events.push({dia:dayNames[d.getDay()],data:String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0'),mes:monthNames[d.getMonth()],hora:s.hora,titulo:s.titulo,ts:eventDate.getTime()})})}return events.sort((a,b)=>a.ts-b.ts)}
function readStoredArray(key,fallback=[]){
  try{
    const raw=localStorage.getItem(key);
    if(raw===null)return fallback;
    const value=JSON.parse(raw);
    if(Array.isArray(value))return value;
  }catch(error){
    console.warn(`[IBNF] Dados locais inválidos em ${key}; usando o padrão seguro.`);
  }
  try{localStorage.removeItem(key)}catch(_){}
  return fallback;
}
const defaultNotices=[{titulo:'Bem-vindo ao app',texto:'Este será o canal oficial de informações da IB Nova Família.'}];
const state={eventos:generateRecurringEvents(),pessoas:readStoredArray('ibnf_pessoas'),aniversariantes:readStoredArray('ibnf_aniversariantes'),avisos:readStoredArray('ibnf_avisos',defaultNotices),user:null,perfil:null};
const panel=document.querySelector('#contentPanel'),modules=document.querySelector('#moduleGrid'),nextSection=document.querySelector('.next-section');
let supa=null;
function supabaseReady(){return !!(window.IBNF_CONFIG?.SUPABASE_URL&&window.IBNF_CONFIG?.SUPABASE_ANON_KEY&&window.supabase)}
if(supabaseReady())supa=window.supabase.createClient(window.IBNF_CONFIG.SUPABASE_URL,window.IBNF_CONFIG.SUPABASE_ANON_KEY);
async function loadSession(){if(!supa)return;const {data}=await supa.auth.getSession();state.user=data.session?.user||null;if(state.user){const {data:perfil}=await supa.from('perfis').select('*').eq('id',state.user.id).maybeSingle();state.perfil=perfil||null}refreshAccessLabel()}
function refreshAccessLabel(){document.querySelectorAll('.login-link').forEach(b=>b.textContent=state.user?(state.perfil?.nome||'Meu perfil'):'Meu acesso')}
function save(){localStorage.setItem('ibnf_pessoas',JSON.stringify(state.pessoas));localStorage.setItem('ibnf_aniversariantes',JSON.stringify(state.aniversariantes));localStorage.setItem('ibnf_avisos',JSON.stringify(state.avisos))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function eventHTML(e,i=0){const parts=String(e.data).split('/');return `<div class="event-item ${i===0?'event-featured':''}"><div class="event-date"><span>${esc(e.dia)}</span><b>${esc(parts[0]||e.data)}</b><small>${esc(e.mes||'')}</small></div><div class="event-title"><small class="event-label">${i===0?'PRÓXIMO EVENTO':'PROGRAMAÇÃO'}</small><b>${esc(e.titulo)}</b><span>🕒 ${esc(e.hora)}</span></div><div class="event-arrow">›</div></div>`}
function renderEvents(){const box=document.querySelector('#nextEvents'),limit=Date.now()+7*24*60*60*1000,next7=state.eventos.filter(e=>e.ts<=limit);if(!next7.length){box.innerHTML='<div class="empty"><div>Não há eventos programados nos próximos 7 dias.</div></div>';return}box.innerHTML=next7.map(eventHTML).join('')}
function showHome(){panel.classList.add('hidden');modules.classList.remove('hidden');nextSection.classList.remove('hidden');setNav('inicio');window.scrollTo({top:0,behavior:'smooth'})}
function openPanel(title,body){modules.classList.add('hidden');nextSection.classList.add('hidden');panel.classList.remove('hidden');panel.innerHTML=`<button class="back-btn" onclick="showHome()">← Voltar</button><h2>${title}</h2>${body}`;window.scrollTo({top:0,behavior:'smooth'})}
function setNav(view){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.desktop-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function isAdmin(){return !!state.user&&['pastor','secretaria'].includes(state.perfil?.perfil)}
function loginPanel(){if(state.user)return `<div class="account-card"><div class="account-logo"><img src="photo_5143638454599093943_y.jpg" alt=""></div><div><span class="section-kicker">Acesso autorizado</span><h3>${esc(state.perfil?.nome||state.user.email)}</h3><p>${esc(state.perfil?.perfil||'usuário')}</p></div></div><div class="permission-grid"><div><b>Conta</b><small>${esc(state.user.email||'')}</small></div><div><b>Perfil</b><small>${esc(state.perfil?.perfil||'Aguardando definição')}</small></div></div>${isAdmin()?'<button class="primary" id="manageUsersBtn" style="margin-top:16px">Gerenciar acessos</button>':''}<button class="secondary-action" id="logoutBtn">Sair da conta</button>`;return `<div class="login-shell"><div class="login-brand"><img src="photo_5143638454599093943_y.jpg" alt="Logo IB Nova Família"><span class="section-kicker">Área restrita</span><h3>Acesso da equipe</h3><p>Entre com seu e-mail e senha para acessar áreas administrativas.</p></div>${!supa?'<div class="setup-notice"><b>Banco ainda não conectado</b><span>A tela de login já está pronta. Falta apenas conectar o projeto ao Supabase.</span></div>':''}<form class="login-form" id="loginForm"><label>E-mail<input name="email" type="email" placeholder="seuemail@exemplo.com" required></label><label>Senha<input name="senha" type="password" placeholder="Sua senha" required></label><button class="primary">Entrar</button></form><button class="secondary-action" id="forgotBtn" type="button">Esqueci minha senha</button><div id="loginFeedback"></div><p style="text-align:center;margin-top:14px"><small>Novos acessos são cadastrados somente pela administração da igreja.</small></p></div>`}
async function bindLogin(){const form=document.querySelector('#loginForm');if(form)form.onsubmit=async e=>{e.preventDefault();const fb=document.querySelector('#loginFeedback');if(!supa){fb.innerHTML='<div class="setup-notice">Conecte o Supabase para ativar o login.</div>';return}const f=new FormData(form),{data,error}=await supa.auth.signInWithPassword({email:f.get('email'),password:f.get('senha')});if(error){fb.innerHTML=`<div class="error-box">${esc(error.message)}</div>`;return}state.user=data.user;await loadSession();showView('perfil')};const forgot=document.querySelector('#forgotBtn');if(forgot)forgot.onclick=async()=>{if(!supa)return;const email=document.querySelector('#loginForm input[name="email"]')?.value.trim();const fb=document.querySelector('#loginFeedback');if(!email){fb.innerHTML='<div class="error-box">Digite seu e-mail acima primeiro.</div>';return}const {error}=await supa.auth.resetPasswordForEmail(email,{redirectTo:location.origin});fb.innerHTML=error?`<div class="error-box">${esc(error.message)}</div>`:'<div class="success">Enviamos as instruções de recuperação para seu e-mail.</div>'};const manage=document.querySelector('#manageUsersBtn');if(manage)manage.onclick=()=>showView('acessos');const out=document.querySelector('#logoutBtn');if(out)out.onclick=async()=>{if(supa)await supa.auth.signOut();state.user=null;state.perfil=null;refreshAccessLabel();showView('perfil')}}
function showView(view){setNav(view);if(view==='inicio'){showHome();return}
if(view==='redes'){openPanel('Redes Sociais','<div class="social-intro"><span class="section-kicker">Conecte-se</span><h3>Acompanhe a IB Nova Família</h3><p>Fique por dentro dos cultos, avisos, mensagens e conteúdos publicados nos nossos canais oficiais.</p></div><div class="social-grid"><a class="social-card instagram" href="https://www.instagram.com/ibnovafamilia/" target="_blank" rel="noopener noreferrer"><span class="social-icon">◎</span><span><b>Instagram</b><small>@ibnovafamilia</small></span><strong>Abrir ›</strong></a><a class="social-card facebook" href="https://www.facebook.com/profile.php?id=61574364590175" target="_blank" rel="noopener noreferrer"><span class="social-icon">f</span><span><b>Facebook</b><small>IB Novafamilia</small></span><strong>Abrir ›</strong></a><a class="social-card whatsapp" href="https://wa.me/5515991570784?text=Paz%20do%20Senhor%21%20Vim%20pelo%20aplicativo%20da%20IB%20Nova%20Fam%C3%ADlia%20e%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es." target="_blank" rel="noopener noreferrer"><span class="social-icon">◉</span><span><b>WhatsApp</b><small>Fale conosco</small></span><strong>Conversar ›</strong></a></div>');return}
if(view==='pessoas'){openPanel('Pessoas','<form class="form" id="pessoaForm"><input name="nome" placeholder="Nome completo" required><input name="telefone" placeholder="Telefone / WhatsApp"><input name="nascimento" type="date"><button class="primary">Cadastrar pessoa</button></form><div id="pessoasLista"></div>');renderPeople();document.querySelector('#pessoaForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.pessoas.push({nome:f.get('nome'),telefone:f.get('telefone'),nascimento:f.get('nascimento')});save();e.target.reset();renderPeople()};return}
if(view==='departamentos'){openPanel('Departamentos','<div class="list-item"><b>Louvor</b><small>Equipe de música e adoração</small></div><div class="list-item"><b>Jovens</b><small>Ministério de juventude</small></div><div class="list-item"><b>Recepção</b><small>Boas-vindas e acolhimento</small></div><div class="list-item"><b>Visitas</b><small>Acompanhamento pastoral</small></div>');return}
if(view==='grupos'){openPanel('Grupos','<div class="list-item"><b>Grupo de Oração</b><small>Comunhão e intercessão</small></div><div class="list-item"><b>Jovens</b><small>Grupo de juventude</small></div>');return}
if(view==='financeiro'){openPanel('Financeiro','<p>Área reservada para tesouraria.</p><p><small>Esta área será protegida por login e permissões.</small></p>');return}
if(view==='estudos'){openPanel('Estudos','<div class="list-item"><b>Estudos bíblicos</b><small>PDFs, séries e materiais poderão ser publicados aqui.</small></div>');return}
if(view==='kids'){openPanel('Kids','<div class="list-item"><b>Ministério Infantil</b><small>Cadastro de crianças, responsáveis e atividades.</small></div>');return}
if(view==='aniversariantes'){openPanel('Aniversariantes','<form class="form" id="aniForm"><input name="nome" placeholder="Nome" required><input name="data" type="date" required><button class="primary">Adicionar aniversariante</button></form><div id="aniLista"></div>');renderBirthdays();document.querySelector('#aniForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.aniversariantes.push({nome:f.get('nome'),data:f.get('data')});save();e.target.reset();renderBirthdays()};return}
if(view==='fotos'){openPanel('Fotos','<div class="empty"><div>Galeria de fotos será adicionada aqui.</div></div>');return}
if(view==='videos'){openPanel('Vídeos','<div class="empty"><div>Vídeos e transmissões ficarão aqui.</div></div>');return}
if(view==='arquivos'){openPanel('Arquivos','<div class="empty"><div>Documentos oficiais e PDFs ficarão aqui.</div></div>');return}
if(view==='oracao'){openPanel('Pedido de oração','<form class="form" id="oracaoForm"><input name="nome" placeholder="Seu nome" required><textarea name="pedido" placeholder="Digite seu pedido de oração" required></textarea><button class="primary">Enviar pedido</button></form><div id="feedback"></div>');document.querySelector('#oracaoForm').onsubmit=e=>{e.preventDefault();const list=JSON.parse(localStorage.getItem('ibnf_oracoes')||'[]');const f=new FormData(e.target);list.push({nome:f.get('nome'),pedido:f.get('pedido'),data:new Date().toISOString()});localStorage.setItem('ibnf_oracoes',JSON.stringify(list));e.target.reset();document.querySelector('#feedback').innerHTML='<div class="success">Pedido registrado para teste.</div>'};return}
if(view==='visitas'){openPanel('Solicitar visita','<form class="form" id="visitaForm"><input name="nome" placeholder="Nome" required><input name="telefone" placeholder="Telefone / WhatsApp" required><textarea name="obs" placeholder="Observação"></textarea><button class="primary">Solicitar visita</button></form><div id="feedback"></div>');document.querySelector('#visitaForm').onsubmit=e=>{e.preventDefault();const list=JSON.parse(localStorage.getItem('ibnf_visitas')||'[]');const f=new FormData(e.target);list.push({nome:f.get('nome'),telefone:f.get('telefone'),obs:f.get('obs'),data:new Date().toISOString()});localStorage.setItem('ibnf_visitas',JSON.stringify(list));e.target.reset();document.querySelector('#feedback').innerHTML='<div class="success">Solicitação registrada para teste.</div>'};return}
if(view==='agenda'){openPanel('Calendário',`<div class="agenda-list">${state.eventos.map(eventHTML).join('')}</div>`);return}
if(view==='notificacoes'){openPanel('Avisos',state.avisos.map(a=>`<div class="list-item"><b>${esc(a.titulo)}</b><small>${esc(a.texto)}</small></div>`).join(''));return}
if(view==='perfil'){openPanel('Meu acesso',loginPanel());bindLogin();return}
if(view==='acessos'){if(!isAdmin()){openPanel('Gerenciar acessos','<div class="error-box">Acesso permitido somente à administração.</div>');return}openPanel('Gerenciar acessos','<div class="social-intro"><span class="section-kicker">Administração</span><h3>Novo acesso da equipe</h3><p>Cadastre o e-mail e uma senha provisória. A pessoa poderá depois recuperar/trocar a senha.</p></div><form class="form" id="accessForm"><input name="nome" placeholder="Nome completo" required><input name="email" type="email" placeholder="E-mail" required><input name="senha" type="password" minlength="6" placeholder="Senha provisória (mín. 6 caracteres)" required><select name="perfil" required><option value="membro">Membro</option><option value="lider">Líder</option><option value="secretaria">Secretaria</option><option value="tesouraria">Tesouraria</option><option value="pastor">Pastor</option></select><button class="primary">Cadastrar acesso</button></form><div id="accessFeedback"></div>');document.querySelector('#accessForm').onsubmit=async e=>{e.preventDefault();const fb=document.querySelector('#accessFeedback'),f=new FormData(e.target);fb.innerHTML='<div class="setup-notice">Criando acesso...</div>';const currentSession=(await supa.auth.getSession()).data.session;const {data,error}=await supa.auth.signUp({email:f.get('email'),password:f.get('senha'),options:{data:{nome:f.get('nome'),perfil:f.get('perfil')}}});if(error){fb.innerHTML=`<div class="error-box">${esc(error.message)}</div>`;return}if(data.user){const {error:pe}=await supa.from('perfis').upsert({id:data.user.id,nome:f.get('nome'),perfil:f.get('perfil'),ativo:true});if(pe){fb.innerHTML=`<div class="error-box">Conta criada, mas o perfil não foi salvo: ${esc(pe.message)}</div>`;return}}if(currentSession)await supa.auth.setSession({access_token:currentSession.access_token,refresh_token:currentSession.refresh_token});fb.innerHTML='<div class="success">Acesso cadastrado. Se a confirmação de e-mail estiver ativa no Supabase, a pessoa deverá confirmar o e-mail antes de entrar.</div>';e.target.reset()};return}
if(view==='menu'){openPanel('Menu','<div class="list-item"><b>Administração</b><small>Cadastros, permissões e configurações.</small></div><div class="list-item"><b>Configurações</b><small>Aparência, notificações e conta.</small></div><div class="list-item"><b>Redes Sociais</b><small>Instagram, Facebook e WhatsApp oficiais da igreja.</small></div>');return}}
function renderPeople(){const el=document.querySelector('#pessoasLista');if(!el)return;el.innerHTML=state.pessoas.length?'<h3 style="margin-top:20px">Cadastrados</h3>'+state.pessoas.map(p=>`<div class="list-item"><b>${esc(p.nome)}</b><small>${esc(p.telefone||'Sem telefone')}</small></div>`).join(''):'<div class="empty"><div>Nenhuma pessoa cadastrada.</div></div>'}
function renderBirthdays(){const el=document.querySelector('#aniLista');if(!el)return;el.innerHTML=state.aniversariantes.length?'<h3 style="margin-top:20px">Cadastrados</h3>'+state.aniversariantes.map(p=>`<div class="list-item"><b>${esc(p.nome)}</b><small>${esc(p.data)}</small></div>`).join(''):'<div class="empty"><div>Nenhum aniversariante cadastrado.</div></div>'}
document.addEventListener('click',event=>{
  const trigger=event.target instanceof Element?event.target.closest('[data-view]'):null;
  if(!trigger||trigger.disabled||!trigger.dataset.view)return;
  const navigate=window.showView;
  if(typeof navigate==='function')navigate(trigger.dataset.view);
});
let deferredPrompt;const installBtn=document.querySelector('#installBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'))}
renderEvents();loadSession();
