(function(){
  if(!window.supabase||!window.IBNF_CONFIG?.SUPABASE_URL)return;
  const sb=window.supabase.createClient(window.IBNF_CONFIG.SUPABASE_URL,window.IBNF_CONFIG.SUPABASE_ANON_KEY),labels={inicio:'Início',agenda:'Agenda',notificacoes:'Avisos',estudos:'Estudos',departamentos:'Ministérios',midia:'Mídia',fotos:'Galeria de fotos',videos:'Vídeos',perfil:'Meu acesso',oracao:'Pedido de oração',visitas:'Solicitar visita',evento_arte:'Arte de evento',compartilhar_evento:'Compartilhar evento'};
  const clean=v=>String(v||'inicio').toLowerCase().replace(/[^a-z0-9_-]/g,'_').slice(0,60),device=()=>matchMedia('(max-width:760px)').matches?'celular':'computador';
  function visitorId(){let id=localStorage.getItem('ibnf_visitante_id');if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem('ibnf_visitante_id',id)}return id}
  async function record(tipo,pagina){try{await sb.from('estatisticas_acessos').insert({visitante_id:visitorId(),tipo:clean(tipo),pagina:clean(pagina),dispositivo:device()})}catch(_){}}
  record('pagina','inicio');const original=window.showView;window.showView=function(view){if(view!=='estatisticas')record('pagina',view);return original(view)};
  document.addEventListener('click',e=>{if(e.target.closest('.campaign-image'))record('clique','evento_arte');if(e.target.closest('[data-share-event],.agenda-share-all,.agenda-share-event,.featured-share'))record('clique','compartilhar_evento')},{passive:true});
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),startDate=days=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-days+1);return d.toISOString()};
  async function render(days=30){if(!window.IBNF_ACCESS?.can?.('estatisticas'))return;window.openPanel?.('Estatísticas','<div class="setup-notice">Carregando os acessos...</div>');const {data,error}=await sb.from('estatisticas_acessos').select('visitante_id,tipo,pagina,dispositivo,criado_em').gte('criado_em',startDate(days)).order('criado_em',{ascending:false}).limit(10000);if(error){window.openPanel?.('Estatísticas',`<div class="error-box"><b>Falta ativar as estatísticas no banco.</b><span>Execute estatisticas-setup.sql no Supabase. ${esc(error.message)}</span></div>`);return}const rows=data||[],pages=rows.filter(r=>r.tipo==='pagina'),visitors=new Set(pages.map(r=>r.visitante_id)),today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),todayVisitors=new Set(pages.filter(r=>new Date(r.criado_em).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})===today).map(r=>r.visitante_id)),counts={};pages.forEach(r=>counts[r.pagina]=(counts[r.pagina]||0)+1);const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8),mobile=pages.filter(r=>r.dispositivo==='celular').length;window.openPanel?.('Estatísticas',`<div class="stats-intro"><div><span class="section-kicker">Acesso exclusivo do pastor</span><h3>Visitas à plataforma</h3><p>Acompanhamento anônimo, sem guardar nome ou e-mail.</p></div><div class="stats-filter">${[7,30,90].map(n=>`<button data-stats-days="${n}" class="${n===days?'active':''}">${n} dias</button>`).join('')}</div></div><div class="stats-grid"><div class="stats-card"><small>Visitantes no período</small><strong>${visitors.size}</strong></div><div class="stats-card"><small>Visitantes hoje</small><strong>${todayVisitors.size}</strong></div><div class="stats-card"><small>Visualizações</small><strong>${pages.length}</strong></div></div><h3>Páginas mais acessadas</h3><div class="stats-list">${ranked.length?ranked.map(([p,n])=>`<div class="stats-row"><span>${esc(labels[p]||p.replaceAll('_',' '))}</span><b>${n}</b></div>`).join(''):'<div class="setup-notice">Ainda não há visitas registradas.</div>'}</div><div class="stats-grid"><div class="stats-card"><small>Acessos por celular</small><strong>${mobile}</strong></div><div class="stats-card"><small>Acessos por computador</small><strong>${pages.length-mobile}</strong></div><div class="stats-card"><small>Cliques em eventos</small><strong>${rows.filter(r=>r.tipo==='clique').length}</strong></div></div><p class="stats-note">A mesma pessoa é contada uma vez como visitante, mesmo que abra várias páginas.</p>`);document.querySelectorAll('[data-stats-days]').forEach(b=>b.onclick=()=>render(Number(b.dataset.statsDays)))}
  const show=window.showView;window.showView=function(view){if(view==='estatisticas'){render();return}return show(view)};
})();
