create table if not exists public.oracao24_config (
  id smallint primary key default 1 check (id = 1),
  titulo text not null check (char_length(trim(titulo)) between 3 and 100),
  versiculo_texto text not null check (char_length(trim(versiculo_texto)) between 2 and 180),
  versiculo_referencia text not null check (char_length(trim(versiculo_referencia)) between 2 and 80),
  descricao text not null check (char_length(trim(descricao)) between 10 and 500),
  inicio timestamptz not null,
  duracao_horas integer not null default 24 check (duracao_horas between 1 and 168),
  ativa boolean not null default true,
  atualizado_em timestamptz not null default now()
);

insert into public.oracao24_config (
  id,
  titulo,
  versiculo_texto,
  versiculo_referencia,
  descricao,
  inicio,
  duracao_horas,
  ativa
)
values (
  1,
  '24 Horas de Oração',
  'Orai sem cessar.',
  '1 Tessalonicenses 5:17',
  'Cada horário corresponde a uma hora de oração. Depois da confirmação, ele ficará reservado em seu nome.',
  timestamptz '2026-09-04 23:00:00-03',
  24,
  true
)
on conflict (id) do nothing;

alter table public.oracao24_config enable row level security;

drop policy if exists "oracao24 config leitura publica" on public.oracao24_config;
create policy "oracao24 config leitura publica"
on public.oracao24_config
for select
to anon, authenticated
using (true);

drop policy if exists "oracao24 config admin insere" on public.oracao24_config;
create policy "oracao24 config admin insere"
on public.oracao24_config
for insert
to authenticated
with check (
  id = 1
  and exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor', 'secretaria')
  )
);

drop policy if exists "oracao24 config admin edita" on public.oracao24_config;
create policy "oracao24 config admin edita"
on public.oracao24_config
for update
to authenticated
using (
  exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor', 'secretaria')
  )
)
with check (
  id = 1
  and exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor', 'secretaria')
  )
);

grant select on public.oracao24_config to anon, authenticated;
grant insert, update on public.oracao24_config to authenticated;

create table if not exists public.oracao24_reservas (
  id bigint generated by default as identity primary key,
  slot_inicio timestamptz not null,
  nome text not null check (char_length(trim(nome)) between 2 and 80),
  criado_em timestamptz not null default now(),
  constraint oracao24_slot_unico unique (slot_inicio)
);

alter table public.oracao24_reservas enable row level security;

drop policy if exists "oracao24 leitura publica" on public.oracao24_reservas;
create policy "oracao24 leitura publica"
on public.oracao24_reservas
for select
to anon, authenticated
using (true);

drop policy if exists "oracao24 reserva publica" on public.oracao24_reservas;
create policy "oracao24 reserva publica"
on public.oracao24_reservas
for insert
to anon, authenticated
with check (
  char_length(trim(nome)) between 2 and 80
  and date_trunc('hour', slot_inicio) = slot_inicio
  and exists (
    select 1
    from public.oracao24_config c
    where c.id = 1
      and c.ativa = true
      and slot_inicio >= c.inicio
      and slot_inicio < c.inicio + make_interval(hours => c.duracao_horas)
  )
);

drop policy if exists "oracao24 admin pode editar" on public.oracao24_reservas;
create policy "oracao24 admin pode editar"
on public.oracao24_reservas
for update
to authenticated
using (
  exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor', 'secretaria')
  )
)
with check (
  char_length(trim(nome)) between 2 and 80
  and date_trunc('hour', slot_inicio) = slot_inicio
  and exists (
    select 1
    from public.oracao24_config c
    where c.id = 1
      and slot_inicio >= c.inicio
      and slot_inicio < c.inicio + make_interval(hours => c.duracao_horas)
  )
  and exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor', 'secretaria')
  )
);

drop policy if exists "oracao24 admin pode liberar" on public.oracao24_reservas;
create policy "oracao24 admin pode liberar"
on public.oracao24_reservas
for delete
to authenticated
using (
  exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor', 'secretaria')
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'oracao24_config'
  ) then
    alter publication supabase_realtime add table public.oracao24_config;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'oracao24_reservas'
  ) then
    alter publication supabase_realtime add table public.oracao24_reservas;
  end if;
end $$;
