create table if not exists public.oracao24_reservas (
  id bigint generated by default as identity primary key,
  slot_inicio timestamptz not null,
  nome text not null check (char_length(trim(nome)) between 2 and 80),
  criado_em timestamptz not null default now(),
  constraint oracao24_slot_unico unique (slot_inicio)
);

alter table public.oracao24_reservas enable row level security;

drop policy if exists "oracao24 leitura publica" on public.oracao24_reservas;
create policy "oracao24 leitura publica"
on public.oracao24_reservas
for select
to anon, authenticated
using (true);

drop policy if exists "oracao24 reserva publica" on public.oracao24_reservas;
create policy "oracao24 reserva publica"
on public.oracao24_reservas
for insert
to anon, authenticated
with check (
  slot_inicio >= timestamptz '2026-09-04 23:00:00-03'
  and slot_inicio < timestamptz '2026-09-05 23:00:00-03'
  and char_length(trim(nome)) between 2 and 80
);

drop policy if exists "oracao24 admin pode liberar" on public.oracao24_reservas;
create policy "oracao24 admin pode liberar"
on public.oracao24_reservas
for delete
to authenticated
using (
  exists (
    select 1
    from public.perfis p
    where p.id = auth.uid()
      and p.perfil in ('pastor','secretaria')
  )
);

alter publication supabase_realtime add table public.oracao24_reservas;