(function(){
 if(!window.supabase||!window.IBNF_CONFIG)return;
 const c=window.supabase.createClient(window.IBNF_CONFIG.SUPABASE_URL,window.IBNF_CONFIG.SUPABASE_ANON_KEY);
 let box;
 function ensure(){if(box)return box;const intro=document.querySelector('.intro-card');if(!intro)return null;box=document.createElement('section');box.id='pastoralHome';box.className='pastoral-home';box.hidden=true;intro.insertAdjacentElement('afterend',box);return box}
 const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 function openTab(tab){if(window.ibnfOpenPastoralSection)window.ibnfOpenPastoralSection(tab);else window.showView('pastoral')}
 window.ibnfOpenPastoralHomeTab=openTab;
 async function refresh(){const el=ensure();if(!el)return;const {data:{session}}=await c.auth.getSession();if(!session){el.hidden=true;el.innerHTML='';return}const {data:p}=await c.from('perfis').select('perfil,ativo').eq('id',session.user.id).maybeSingle();if(!p?.ativo||p.perfil!=='pastor'){el.hidden=true;el.innerHTML='';return}
 const [o,v,vi,s]=await Promise.all([c.from('pedidos_oracao').select('id,status,nome,pedido,criado_em').order('criado_em',{ascending:false}),c.from('visitas').select('id,status,nome,telefone,observacao,criado_em').order('criado_em',{ascending:false}),c.from('visitantes').select('id,status,nome,telefone,observacao,criado_em').order('criado_em',{ascending:false}),c.from('quero_servir').select('id,status,nome,telefone,area,observacao,criado_em').order('criado_em',{ascending:false})]);
 const O=(o.data||[]).filter(x=>x.status!=='concluido'),V=(v.data||[]).filter(x=>x.status!=='realizada'),VI=(vi.data||[]).filter(x=>x.status!=='concluido'),S=(s.data||[]).filter(x=>x.status!=='concluido');const total=O.length+V.length+VI.length+S.length;
 const preview=(arr,type)=>arr.slice(0,3).map(x=>{let txt=type==='oracao'?x.pedido:type==='servir'?[x.area,x.observacao].filter(Boolean).join(' · '):[x.telefone,x.observacao].filter(Boolean).join(' · ');return `<button class="pastoral-preview" onclick="ibnfOpenPastoralHomeTab('${type}')"><b>${esc(x.nome)}</b><span>${esc(txt)}</span></button>`}).join('');
 el.hidden=false;el.innerHTML=`<div class="pastoral-home-head"><div><span class="section-kicker">Área do Pastor</span><h2>Pendências Pastorais</h2><p>${total?`Você tem ${total} ${total===1?'solicitação pendente':'solicitações pendentes'} para acompanhar.`:'Nenhuma solicitação pendente no momento.'}</p></div><button class="outline-action" onclick="ibnfOpenPastoralHomeTab('resumo')">Abrir Painel Pastoral</button></div><div class="pastoral-home-grid"><button onclick="ibnfOpenPastoralHomeTab('oracao')"><b>${O.length}</b><span>Pedidos de oração</span></button><button onclick="ibnfOpenPastoralHomeTab('visitas')"><b>${V.length}</b><span>Visitas</span></button><button onclick="ibnfOpenPastoralHomeTab('visitantes')"><b>${VI.length}</b><span>Visitantes</span></button><button onclick="ibnfOpenPastoralHomeTab('servir')"><b>${S.length}</b><span>Quero servir</span></button></div>${O.length?`<div class="pastoral-home-list"><h3>Pedidos de oração recentes</h3>${preview(O,'oracao')}</div>`:''}${V.length?`<div class="pastoral-home-list"><h3>Visitas recentes</h3>${preview(V,'visitas')}</div>`:''}${VI.length?`<div class="pastoral-home-list"><h3>Visitantes recentes</h3>${preview(VI,'visitantes')}</div>`:''}${S.length?`<div class="pastoral-home-list"><h3>Quero servir</h3>${preview(S,'servir')}</div>`:''}`}
 c.auth.onAuthStateChange(()=>setTimeout(refresh,100));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh);else refresh();window.ibnfRefreshPastoralHome=refresh;
})();